package lint_test

import (
	"testing"

	helpers "jsapi-scraper/helpers"
)

var names = []string{
	"Apple Iphone 6S",
	"Apple Iphone 8",
	"Apple Iphone Se",
	"Blackview Bv4900",
	"Blackview Bv4900 Pro",
	"Blackview Bv6300 Pro",
	"Energizer E241s",
	"Fairphone 2",
	"Honor Magic4 Lite",
	"Honor X6",
	"Huawei Mate 20",
	"Huawei Mate S",
	"Huawei Nova",
	"Huawei Nova 9",
	"Huawei Nova 9 Se",
	"Huawei Nova Y70",
	"Huawei Nova Y90",
	"Huawei P Smart",
	"Huawei P30",
	"Huawei P40",
	"Huawei P40 Lite",
	"Huawei P9 Lite",
	"Huawei Y5p",
	"Huawei Y6p",
	"Microsoft Lumia 650",
	"Motorola Defy",
	"Motorola Moto C Plus",
	"Motorola Moto E13",
	"Motorola Moto E20",
	"Motorola Moto E22",
	"Motorola Moto E22i",
	"Motorola Moto E32",
	"Motorola Moto E32s",
	"Motorola Moto E40",
	"Motorola Moto G 2Nd Gen",
	"Motorola Moto G10",
	"Motorola Moto G22",
	"Motorola Moto G23",
	"Motorola Moto G31",
	"Motorola Moto G32",
	"Motorola Moto G41",
	"Motorola Moto G42",
	"Motorola Moto G5 Plus",
	"Motorola Moto G52",
	"Motorola Moto G 6",
	"Motorola Moto G71",
	"Motorola Moto G72",
	"Nokia 1.4",
	"Nokia 105",
	"Nokia 110",
	"Nokia 150",
	"Nokia 225",
	"Nokia 2660",
	"Nokia 2720 Flip",
	"Nokia 3310",
	"Nokia 5710 Xa",
	"Nokia 800 Tough",
	"Nokia 8210",
	"Nokia C12",
	"Nokia C21",
	"Nokia C21 Plus",
	"Nokia G10",
	"Nokia G11",
	"Nokia G20",
	"Nokia G21",
	"Nokia G22",
	"Nokia G50",
	"Nokia G60",
	"Nokia X10",
	"Nokia X20",
	"Oneplus 8",
	"Oneplus Nord",
	"Oneplus Nord Ce 2 Lite",
	"Oppo A16s",
	"Oppo A5",
	"Oppo A54",
	"Oppo A54s",
	"Oppo A57s",
	"Oppo A76",
	"Oppo A9",
	"Oppo A91",
	"Oppo A94",
	"Oppo A96",
	"Oppo Find X2 Lite",
	"Oppo Reno 2",
	"Oppo Reno 8 Lite",
	"Oppo Reno4 Z",
	"Oukitel Wp18",
	"Oukitel Wp5 Pro",
	"Realme 8",
	"Realme 8I",
	"Realme 9",
	"Realme 9 Pro",
	"Realme 9I",
	"Realme C11",
	"Realme C21",
	"Realme C21y",
	"Realme C25y",
	"Realme C30",
	"Realme C31",
	"Realme C33",
	"Realme C35",
	"Realme Gt Master",
	"Realme Narzo 50A Prime",
	"Samsung Galaxy A04s",
	"Samsung Galaxy A12",
	"Samsung Galaxy A13",
	"Samsung Galaxy A14",
	"Samsung Galaxy A22",
	"Samsung Galaxy A23",
	"Samsung Galaxy A3",
	"Samsung Galaxy A32",
	"Samsung Galaxy A51",
	"Samsung Galaxy A8",
	"Samsung Galaxy M13",
	"Samsung Galaxy M23",
	"Samsung Galaxy S10",
	"Samsung Galaxy S10e",
	"Samsung Galaxy S20 Fe",
	"Samsung Galaxy S8",
	"Samsung Galaxy S9",
	"Samsung Galaxy Xcover 5",
	"Sony Xperia Z5 Premium",
	"Ulefone Armor X11 Pro",
	"Vivo Y01",
	"Vivo Y21",
	"Vivo Y21s",
	"Vivo Y33s",
	"Vivo Y52",
	"Wiko Power U10",
	"Wiko Y52",
	"Xiaomi 11 Lite",
	"Xiaomi Mi 10 Lite",
	"Xiaomi Mi 10T Lite",
	"Xiaomi Mi 11 Lite",
	"Xiaomi Mi 8",
	"Xiaomi Mi 8 Lite",
	"Xiaomi Mi Mix 2S",
	"Xiaomi Poco C40",
	"Xiaomi Poco M4",
	"Xiaomi Poco M5",
	"Xiaomi Poco M5s",
	"Xiaomi Poco X5",
	"Xiaomi Redmi 10",
	"Xiaomi Redmi 10A",
	"Xiaomi Redmi 10C",
	"Xiaomi Redmi 8A",
	"Xiaomi Redmi 9",
	"Xiaomi Redmi 9A",
	"Xiaomi Redmi 9At",
	"Xiaomi Redmi 9C",
	"Xiaomi Redmi 9T",
	"Xiaomi Redmi A1",
	"Xiaomi Redmi Note 10",
	"Xiaomi Redmi Note 10 Pro",
	"Xiaomi Redmi Note 10S",
	"Xiaomi Redmi Note 11",
	"Xiaomi Redmi Note 11 Pro",
	"Xiaomi Redmi Note 11S",
	"Xiaomi Redmi Note 7",
	"Xiaomi Redmi Note 8T",
	"Xiaomi Redmi Note 9",
	"Zte Blade A31",
	"Zte Blade A31 Lite",
	"Zte Blade A52",
	"Zte Blade A72",
	"Zte Blade V30",
	"Zte Blade V30 Vita",
	"Zte Blade V40 Vita",
}

var namesExpected = []string{
	"Apple iPhone 6S",
	"Apple iPhone 8",
	"Apple iPhone SE",
	"Blackview BV4900",
	"Blackview BV4900 Pro",
	"Blackview BV6300 Pro",
	"Energizer E241s",
	"Fairphone 2",
	"HONOR Magic4 Lite",
	"HONOR X6",
	"HUAWEI Mate 20",
	"HUAWEI Mate S",
	"HUAWEI nova",
	"HUAWEI nova 9",
	"HUAWEI nova 9 SE",
	"HUAWEI nova Y70",
	"HUAWEI nova Y90",
	"HUAWEI P smart",
	"HUAWEI P30",
	"HUAWEI P40",
	"HUAWEI P40 lite",
	"HUAWEI P9 lite",
	"HUAWEI Y5p",
	"HUAWEI Y6p",
	"Microsoft Lumia 650",
	"motorola defy",
	"motorola moto c plus",
	"motorola moto e13",
	"motorola moto e20",
	"motorola moto e22",
	"motorola moto e22i",
	"motorola moto e32",
	"motorola moto e32s",
	"motorola moto e40",
	"motorola moto g 2nd gen",
	"motorola moto g10",
	"motorola moto g22",
	"motorola moto g23",
	"motorola moto g31",
	"motorola moto g32",
	"motorola moto g41",
	"motorola moto g42",
	"motorola moto g5 plus",
	"motorola moto g52",
	"motorola moto g6",
	"motorola moto g71",
	"motorola moto g72",
	"Nokia 1.4",
	"Nokia 105",
	"Nokia 110",
	"Nokia 150",
	"Nokia 225",
	"Nokia 2660",
	"Nokia 2720 Flip",
	"Nokia 3310",
	"Nokia 5710 XA",
	"Nokia 800 Tough",
	"Nokia 8210",
	"Nokia C12",
	"Nokia C21",
	"Nokia C21 Plus",
	"Nokia G10",
	"Nokia G11",
	"Nokia G20",
	"Nokia G21",
	"Nokia G22",
	"Nokia G50",
	"Nokia G60",
	"Nokia X10",
	"Nokia X20",
	"OnePlus 8",
	"OnePlus Nord",
	"OnePlus Nord CE 2 Lite",
	"OPPO A16s",
	"OPPO A5",
	"OPPO A54",
	"OPPO A54s",
	"OPPO A57s",
	"OPPO A76",
	"OPPO A9",
	"OPPO A91",
	"OPPO A94",
	"OPPO A96",
	"OPPO Find X2 Lite",
	"OPPO Reno2",
	"OPPO Reno8 Lite",
	"OPPO Reno4 Z",
	"OUKITEL WP18",
	"OUKITEL WP5 Pro",
	"realme 8",
	"realme 8i",
	"realme 9",
	"realme 9 Pro",
	"realme 9i",
	"realme C11",
	"realme C21",
	"realme C21Y",
	"realme C25Y",
	"realme C30",
	"realme C31",
	"realme C33",
	"realme C35",
	"realme GT Master",
	"realme narzo 50A Prime",
	"Samsung Galaxy A04s",
	"Samsung Galaxy A12",
	"Samsung Galaxy A13",
	"Samsung Galaxy A14",
	"Samsung Galaxy A22",
	"Samsung Galaxy A23",
	"Samsung Galaxy A3",
	"Samsung Galaxy A32",
	"Samsung Galaxy A51",
	"Samsung Galaxy A8",
	"Samsung Galaxy M13",
	"Samsung Galaxy M23",
	"Samsung Galaxy S10",
	"Samsung Galaxy S10e",
	"Samsung Galaxy S20 FE",
	"Samsung Galaxy S8",
	"Samsung Galaxy S9",
	"Samsung Galaxy XCover 5",
	"Sony Xperia Z5 Premium",
	"Ulefone Armor X11 Pro",
	"vivo Y01",
	"vivo Y21",
	"vivo Y21s",
	"vivo Y33s",
	"vivo Y52",
	"Wiko Power U10",
	"Wiko Y52",
	"Xiaomi 11 Lite",
	"Xiaomi Mi 10 Lite",
	"Xiaomi Mi 10T Lite",
	"Xiaomi Mi 11 Lite",
	"Xiaomi Mi 8",
	"Xiaomi Mi 8 Lite",
	"Xiaomi Mi Mix 2S",
	"Xiaomi POCO C40",
	"Xiaomi POCO M4",
	"Xiaomi POCO M5",
	"Xiaomi POCO M5s",
	"Xiaomi POCO X5",
	"Xiaomi Redmi 10",
	"Xiaomi Redmi 10A",
	"Xiaomi Redmi 10C",
	"Xiaomi Redmi 8A",
	"Xiaomi Redmi 9",
	"Xiaomi Redmi 9A",
	"Xiaomi Redmi 9AT",
	"Xiaomi Redmi 9C",
	"Xiaomi Redmi 9T",
	"Xiaomi Redmi A1",
	"Xiaomi Redmi Note 10",
	"Xiaomi Redmi Note 10 Pro",
	"Xiaomi Redmi Note 10S",
	"Xiaomi Redmi Note 11",
	"Xiaomi Redmi Note 11 Pro",
	"Xiaomi Redmi Note 11S",
	"Xiaomi Redmi Note 7",
	"Xiaomi Redmi Note 8T",
	"Xiaomi Redmi Note 9",
	"ZTE Blade A31",
	"ZTE Blade A31 Lite",
	"ZTE Blade A52",
	"ZTE Blade A72",
	"ZTE Blade V30",
	"ZTE Blade V30 Vita",
	"ZTE Blade V40 Vita",
}

func TestLint(t *testing.T) {
	for i, name := range names {
		if _name := helpers.Lint(name); _name != namesExpected[i] {
			t.Errorf("given name \"%s\" not match expected name \"%s\"\n", name, _name)
		}
	}
}

func TestModel(t *testing.T) {
	for _, name := range names {
		helpers.Model(name)
	}
}
