package shop_test

import (
	shop "jsapi-scraper/shop"
	"testing"
)

var galaxusNames = []string{
	"Apple iPhone 11 Pro",
	"Apple iPhone 6",
	"Apple iPhone 7",
	"Apple iPhone 8",
	"Apple iPhone SE (2nd Gen)",
	"Apple iPhone XS",
	"Blackview A100 DUAL SIM 128GB Blue",
	"Blackview A55GREEN Phone A55 / Green",
	"Blackview MOBILE PHONE A70/BLUE",
	"Blackview BL5000 5G 8",
	"Blackview BV4900 Pro (5.7 Zoll) Dual-SIM Android 10.0 Mikro-USB",
	"Blackview BV5200 Pro 5180 mAh 4/64 GB Schwarz (schwarz) Smartphone",
	"Blackview BV7100 13000 mAh 6/128 GB Grünes Smartphone",
	"Blackview Smartfon BV5300 czarny",
	"Blackview Smartfon BV5300 zielony",
	"Blackview Smartfon BV5300 PRO pomarańczowy",
	"Blackview Smartphone Blackview Smartphone BV9900E 6/128 Silver",
	"Blackview Smartphone Blackview BV9200 8/256 Orange",
	"Fairphone 2",
	"Google Pixel 3a",
	"Google Pixel 4a",
	"Google Pixel 4a 5G",
	"Google Pixel 6a",
	"Honor 70",
	"Honor 8",
	"Honor 90 LITE 8G/256G MIDNIGHT BLACK",
	"Honor Magic 4 Lite 5G",
	"HTC Desire 22 Pro",
	"Huawei Mate S Force Touch",
	"Huawei Nova 10 SE",
	"Huawei Nova 8I",
	"Huawei nova 9",
	"Huawei Nova 9 SE",
	"Huawei Nova Y70",
	"Huawei Nova Y90",
	"Huawei P40 Lite",
	"Huawei P40 Lite + Huawei Bluetooth Speaker",
	"Huawei P8",
	"Huawei Porsche Design Mate 10",
	"Huawei Y5p",
	"Infinix Hot 11 X689F",
	"Infinix HOT 11S 17 2 cm (6.78 Zoll) Dual-SIM Android 11 4G USB Typ-C 6 GB 128 GB 5000 mAh Schwarz",
	"Infinix HOT205G4128BL smartphone (6.6\") Dual SIM Android 12 USB Type-C Silver",
	"Infinix HOT205G4128BK smartphone (6.6\") Dual SIM Android 12 Black",
	"Infinix INFINIX Smart 6 hellblau",
	"Infinix NOTE 12 PRO (6.7\") Dual SIM Android 12 USB Type-C Black",
	"Infinix Smartphone Infinix Hot 11S 4/64GB Dual SIM Grün (X6812B4GW)",
	"Infinix Telefon SMART 6 HD/2/32GB FORCE Schwarz INFINIX",
	"Maxcom Telefonas MM 827 4G VoLTE",
	"Motorola 41",
	"Motorola Defy",
	"Motorola e22",
	"Motorola E22i",
	"Motorola Edge 20",
	"Motorola EDGE 20 LITE 8 / 128GB LAGOON Green",
	"Motorola Edge 30",
	"Motorola Edge 30 5G OLED Dual SIM 256/8GB Aurora Green",
	"Motorola G42",
	"Motorola Google Nexus 6",
	"Motorola Moto E 13 16 5 cm (6.5 Zoll) Dual-SIM Android 13 Go edition 4G USB Typ-C 2 GB 64 GB 5000 mA",
	"Motorola Moto E13 16,5 cm (6,5\") Dual-SIM Android 13 Go Edition 4G USB Type-C 2 GB 64 GB 5000 mAh Kapazität",
	"Motorola Moto E20 2 ”",
	"Motorola Moto E32",
	"Motorola Moto E32s Dual SIM, 4GB RAM, 64GB, Misty Silver",
	"Motorola Moto Edge 30 Neo",
	"Motorola Moto Edge30 Neo",
	"Motorola Moto G 5G",
	"Motorola Moto G 5G Plus",
	"Motorola Moto G10",
	"Motorola Moto G200",
	"Motorola moto g22 16.5 cm (6.5\") Dual SIM Android 12 4G USB Type-C 4 GB 64 GB 5000 mAh Juodas",
	"Motorola Moto G30",
	"Motorola Moto G31 4",
	"Motorola Moto G41 (4GB)",
	"Motorola Moto G42 4",
	"Motorola Moto G5 Plus",
	"Motorola Moto G52",
	"Motorola Moto G5s Plus",
	"Motorola Moto G6 Play",
	"Motorola Moto G62 5G",
	"Motorola Moto G73 5G Phone, 256/8 GB, Midnight Blue",
	"Motorola Motorola Moto G53",
	"Motorola Smartfon Motorola Moto G13 4/128GB Matte Charcoal",
	"Motorola SMARTPHONE MOTOROLA MOTO G53 5G 4/128 ARCTIC Silber",
	"Motorola XT2143-1 Edge 20 Grey EU Android",
	"Nokia 3.4",
	"Nokia 7.1",
	"Nokia G11",
	"Nokia G20",
	"Nokia G21",
	"Nokia G22 Blue",
	"Nokia G50",
	"Nokia Handy lyra 110 4g ds ta-1386 juoda",
	"Nokia Lumia 930",
	"Nokia Smartphone G11 DS 3",
	"Nokia X20 (6GB)",
	"Nokia XR20",
	"OnePlus 3T",
	"OnePlus 5T",
	"OnePlus 6",
	"OnePlus 6T (8GB)",
	"OnePlus 7T (8GB)",
	"OnePlus 8T (12GB)",
	"OnePlus 8 Pro Limited (12GB)",
	"OnePlus Nord 2",
	"OnePlus Nord 2 (12GB)",
	"OnePlus Nord 2 (8GB)",
	"OnePlus Nord 2T",
	"OnePlus Nord CE",
	"OnePlus Nord CE 2 Lite 5G",
	"OnePlus Nord CE3 Lite 5G Pastel Lime",
	"OPPO 8 Lite",
	"OPPO A57s",
	"OPPO A74",
	"OPPO A74 5G Space Silver",
	"OPPO Find X2 Lite",
	"OPPO Find X3 Lite",
	"OPPO Find X3 Neo",
	"OPPO Find X5 Lite",
	"OPPO OPP DS RENO8 LITE 5G 8+128 OEM EU BLK",
	"OPPO Reno 7 Lite",
	"OPPO Reno 8 Lite",
	"OPPO Reno4 Pro",
	"OPPO Reno4 Z",
	"OPPO Reno6",
	"OPPO Smartphone A57s 4",
	"OPPO Smartphone oppo reno 8 lite 8/128gb schwarz",
	"Poco M4 Pro",
	"POCO MOBILE PHONE X5 5G/6/128GB BLACK MZB0D5REU",
	"realme 7 Pro",
	"realme C30 bamboo green 3+32GB",
	"realme GT Master",
	"realme GT Master Edition",
	"realme Narzo 50 4g 128 GB Speed Blue",
	"Renewd iPhone SE2020",
	"Rephone Rephone",
	"Samsung Galaxy A12 (2021)",
	"Samsung Galaxy A13",
	"Samsung Galaxy A13 EU",
	"Samsung Galaxy A14 LTE",
	"Samsung Galaxy A21s DE",
	"Samsung Galaxy A32",
	"Samsung Galaxy A32 5G",
	"Samsung Galaxy A32 EU",
	"Samsung Galaxy A33 5G",
	"Samsung Galaxy A33 5G EU",
	"Samsung Galaxy A52",
	"Samsung Galaxy A52s",
	"Samsung Galaxy A52s EU",
	"Samsung Galaxy A53 5G",
	"Samsung Galaxy A53 5G EU",
	"Samsung Galaxy A72",
	"Samsung Galaxy Note 20 Ultra Snapdragon",
	"Samsung Galaxy Note 4",
	"Samsung Galaxy Note 9",
	"Samsung Galaxy S20 FE 5G",
	"Samsung Galaxy XCover 4s",
	"Samsung Galaxy XCover 5 EE Enterprise Edition",
	"Samsung Galaxy XCover Pro EE Enterprise Edition",
	"Samsung Galaxy Z Flip3 5G EU",
	"Sony Xperia 1",
	"Sony Xperia 10 III",
	"Sony Xperia XZ",
	"Sony Xperia Z3 Compact, Schwarz",
	"Sony Xperia Z3+",
	"Sony Xperia Z5 Compact - The Bond Phone",
	"Sony Xperia Z5 Premium",
	"TCL 30E (6.52 Zoll) Dual-SIM Android 12 USB Typ-C",
	"TCL 40 40SE 17,1 cm (6.75\" ) Dual-SIM Android 13 4G USB Typ-C 6 GB 256 GB 5010 mAh Violett",
	"TCL 403 15,2 cm (6\" ) Dual-SIM Android 12 Go Edition 4G Mikro-USB 2 GB 32 GB 3000 mAh Malve",
	"TCL TCT 30 17 cm (6.7\" ) Dual-SIM Android 12 4G USB Typ-C 4 GB 64 GB 5010 mAh Blau",
	"TE Connectivity ZTE Blade A71",
	"TIM HONOR Magic5 Lite",
	"TIM moto g53 5g",
	"TIM SAM DS A236B GAL A23 5G 4+128 TIM BLK",
	"Vivo NEX S",
	"Vivo X60 Pro 5G",
	"Vivo Y01 Elegant Black",
	"Vivo Y21 Pearl White",
	"Vivo Y21s midday dream",
	"Vivo Y21s midnight blue",
	"Vivo Y72 5G (V2041) dream glow",
	"Vivo Y76 5G Cosmic Aurora",
	"Vivo Y76 5G Midnight Space",
	"Vodafone Samsung Galaxy A33",
	"Xiaomi 11 Lite 5G NE",
	"Xiaomi 11T",
	"Xiaomi 11T 5G",
	"Xiaomi 11T Pro",
	"Xiaomi Honor Magic5 Lite",
	"Xiaomi M5 6/128GB GELB",
	"Xiaomi Mi 10 Lite 5G",
	"Xiaomi Mi 10T Pro",
	"Xiaomi Mi 11 Lite",
	"Xiaomi Mi 11 Lite 5G (8GB)",
	"Xiaomi Mi 9",
	"Xiaomi M5s",
	"Xiaomi Poco F3",
	"Xiaomi Poco M3",
	"Xiaomi POCO M4 5G",
	"Xiaomi Poco X3",
	"Xiaomi Poco X4 Pro",
	"Xiaomi Poco X4 Pro 5G",
	"Xiaomi Redmi10 2022",
	"Xiaomi Redmi 10",
	"Xiaomi Redmi 10 Dual-Sim (2022) 64GB, Sea Blue",
	"Xiaomi Redmi 10C",
	"Xiaomi Redmi 12C (Ocean Blue) DS 6.71“ IPS LCD 720x1650/2.0GHz&1.8GHz/32GB/3GB RAM/MIUI 13/microSDXC",
	"Xiaomi Redmi 9",
	"Xiaomi Redmi 9C NFC",
	"Xiaomi Redmi A1 Plus",
	"Xiaomi Redmi A1+ Dual Sim 32GB, 2GB RAM, Blue",
	"Xiaomi Redmi A2 2/32 GB blue EU",
	"Xiaomi Redmi Note 10",
	"Xiaomi Redmi Note 10 Pro",
	"Xiaomi Redmi Note 10S",
	"Xiaomi Redmi Note 11",
	"Xiaomi Redmi Note 11 Pro",
	"Xiaomi Redmi Note 11 Pro 5G (6GB)",
	"Xiaomi Redmi Note 11 Pro+ 5G",
	"Xiaomi Redmi Note 11s 5G Dual Sim 4GB RAM 128GB - Twilight Blue EU",
	"Xiaomi Redmi Note 12 OEM",
	"Xiaomi Redmi Note 8",
	"Xiaomi Redmi Note 8 Pro",
	"Xiaomi Redmi Note 9",
	"Xiaomi Redmi Note 9 Pro",
	"Xiaomi Samsung Galaxy A14 5G",
	"Xiaomi X5 6/128GB blue EU",
	"Xiaomi Xia Redmi 10 (2022) 128-4-4G-wh Xia Redmi 10 2022 LTE 128/4 Pebble White",
	"Xiaomi Xiaomi 12 Lite",
	"ZTE Blade A31",
	"ZTE Blade A31 Lite",
	"ZTE Blade V40 Vita 128G+4G black(inkl. Buds",
	"ZTE Blade V40S 4G Black",
	"ZTE Graues Smartphone Blade V40 Design + schwarze Smartwatch Watch Live",
	"ZTE Smartphone A310 1/8GB Graphit (A31232/GY)",
	"ZTE Supplier did not provide product name",
}

var galaxusNamesExpected = []string{
	"Apple iPhone 11 Pro",
	"Apple iPhone 6",
	"Apple iPhone 7",
	"Apple iPhone 8",
	"Apple iPhone SE (2020)",
	"Apple iPhone XS",
	"Blackview A100",
	"Blackview A55",
	"Blackview A70",
	"Blackview BL5000",
	"Blackview BV4900 Pro",
	"Blackview BV5200 Pro",
	"Blackview BV7100",
	"Blackview BV5300",
	"Blackview BV5300",
	"Blackview BV5300 PRO",
	"Blackview BV9900E",
	"Blackview BV9200",
	"Fairphone 2",
	"Google Pixel 3a",
	"Google Pixel 4a",
	"Google Pixel 4a",
	"Google Pixel 6a",
	"Honor 70",
	"Honor 8",
	"Honor 90 LITE",
	"Honor Magic4 Lite",
	"HTC Desire 22 Pro",
	"Huawei Mate S",
	"Huawei Nova 10 SE",
	"Huawei Nova 8I",
	"Huawei nova 9",
	"Huawei Nova 9 SE",
	"Huawei Nova Y70",
	"Huawei Nova Y90",
	"Huawei P40 Lite",
	"Huawei P40 Lite",
	"Huawei P8",
	"Huawei Mate 10",
	"Huawei Y5p",
	"Infinix Hot 11",
	"Infinix HOT 11S",
	"Infinix HOT 20",
	"Infinix HOT 20",
	"Infinix Smart 6",
	"Infinix NOTE 12 PRO",
	"Infinix Hot 11S",
	"Infinix SMART 6 HD",
	"Maxcom MM 827",
	"Motorola Moto G41",
	"Motorola Defy",
	"Motorola Moto e22",
	"Motorola Moto E22i",
	"Motorola Edge 20",
	"Motorola EDGE 20 LITE",
	"Motorola Edge 30",
	"Motorola Edge 30",
	"Motorola Moto G42",
	"Motorola Google Nexus 6",
	"Motorola Moto E13",
	"Motorola Moto E13",
	"Motorola Moto E20",
	"Motorola Moto E32",
	"Motorola Moto E32s",
	"Motorola Edge 30 Neo",
	"Motorola Edge 30 Neo",
	"Motorola Moto G",
	"Motorola Moto G Plus",
	"Motorola Moto G10",
	"Motorola Moto G200",
	"Motorola moto g22",
	"Motorola Moto G30",
	"Motorola Moto G31",
	"Motorola Moto G41",
	"Motorola Moto G42",
	"Motorola Moto G5 Plus",
	"Motorola Moto G52",
	"Motorola Moto G5s Plus",
	"Motorola Moto G6 Play",
	"Motorola Moto G62",
	"Motorola Moto G73",
	"Motorola Moto G53",
	"Motorola Moto G13",
	"Motorola MOTO G53",
	"Motorola Edge 20",
	"Nokia 3.4",
	"Nokia 7.1",
	"Nokia G11",
	"Nokia G20",
	"Nokia G21",
	"Nokia G22",
	"Nokia G50",
	"Nokia lyra 110",
	"Nokia Lumia 930",
	"Nokia G11",
	"Nokia X20",
	"Nokia XR20",
	"OnePlus 3T",
	"OnePlus 5T",
	"OnePlus 6",
	"OnePlus 6T",
	"OnePlus 7T",
	"OnePlus 8T",
	"OnePlus 8 Pro",
	"OnePlus Nord 2",
	"OnePlus Nord 2",
	"OnePlus Nord 2",
	"OnePlus Nord 2T",
	"OnePlus Nord CE",
	"OnePlus Nord CE 2 Lite",
	"OnePlus Nord CE 3 Lite",
	"OPPO Reno8 Lite",
	"OPPO A57s",
	"OPPO A74",
	"OPPO A74",
	"OPPO Find X2 Lite",
	"OPPO Find X3 Lite",
	"OPPO Find X3 Neo",
	"OPPO Find X5 Lite",
	"OPPO RENO8 LITE",
	"OPPO Reno7 Lite",
	"OPPO Reno8 Lite",
	"OPPO Reno4 Pro",
	"OPPO Reno4 Z",
	"OPPO Reno6",
	"OPPO A57s",
	"OPPO Reno8 lite",
	"Xiaomi Poco M4 Pro",
	"Xiaomi POCO X5",
	"realme 7 Pro",
	"realme C30",
	"realme GT",
	"realme GT",
	"realme Narzo 50",
	"Apple iPhone SE (2020)",
	"Rephone",
	"Samsung Galaxy A12",
	"Samsung Galaxy A13",
	"Samsung Galaxy A13",
	"Samsung Galaxy A14",
	"Samsung Galaxy A21s",
	"Samsung Galaxy A32",
	"Samsung Galaxy A32",
	"Samsung Galaxy A32",
	"Samsung Galaxy A33",
	"Samsung Galaxy A33",
	"Samsung Galaxy A52",
	"Samsung Galaxy A52s",
	"Samsung Galaxy A52s",
	"Samsung Galaxy A53",
	"Samsung Galaxy A53",
	"Samsung Galaxy A72",
	"Samsung Galaxy Note 20 Ultra",
	"Samsung Galaxy Note 4",
	"Samsung Galaxy Note 9",
	"Samsung Galaxy S20 FE",
	"Samsung Galaxy XCover 4s",
	"Samsung Galaxy XCover 5",
	"Samsung Galaxy XCover Pro",
	"Samsung Galaxy Z Flip3",
	"Sony Xperia 1",
	"Sony Xperia 10 III",
	"Sony Xperia XZ",
	"Sony Xperia Z3 Compact",
	"Sony Xperia Z3+",
	"Sony Xperia Z5 Compact",
	"Sony Xperia Z5 Premium",
	"TCL 30E",
	"TCL 40SE",
	"TCL 403",
	"TCL 30",
	"ZTE Blade A71",
	"HONOR Magic5 Lite",
	"MOTOROLA moto g53",
	"SAMSUNG GALAXY A23",
	"Vivo NEX S",
	"Vivo X60 Pro",
	"Vivo Y01",
	"Vivo Y21",
	"Vivo Y21s",
	"Vivo Y21s",
	"Vivo Y72",
	"Vivo Y76",
	"Vivo Y76",
	"Samsung Galaxy A33",
	"Xiaomi 11 Lite",
	"Xiaomi 11T",
	"Xiaomi 11T",
	"Xiaomi 11T Pro",
	"Honor Magic5 Lite",
	"Xiaomi Poco M5",
	"Xiaomi Mi 10 Lite",
	"Xiaomi Mi 10T Pro",
	"Xiaomi Mi 11 Lite",
	"Xiaomi Mi 11 Lite",
	"Xiaomi Mi 9",
	"Xiaomi Poco M5s",
	"Xiaomi Poco F3",
	"Xiaomi Poco M3",
	"Xiaomi POCO M4",
	"Xiaomi Poco X3",
	"Xiaomi Poco X4 Pro",
	"Xiaomi Poco X4 Pro",
	"Xiaomi Redmi 10",
	"Xiaomi Redmi 10",
	"Xiaomi Redmi 10",
	"Xiaomi Redmi 10C",
	"Xiaomi Redmi 12C",
	"Xiaomi Redmi 9",
	"Xiaomi Redmi 9C",
	"Xiaomi Redmi A1+",
	"Xiaomi Redmi A1+",
	"Xiaomi Redmi A2",
	"Xiaomi Redmi Note 10",
	"Xiaomi Redmi Note 10 Pro",
	"Xiaomi Redmi Note 10S",
	"Xiaomi Redmi Note 11",
	"Xiaomi Redmi Note 11 Pro",
	"Xiaomi Redmi Note 11 Pro",
	"Xiaomi Redmi Note 11 Pro+",
	"Xiaomi Redmi Note 11s",
	"Xiaomi Redmi Note 12",
	"Xiaomi Redmi Note 8",
	"Xiaomi Redmi Note 8 Pro",
	"Xiaomi Redmi Note 9",
	"Xiaomi Redmi Note 9 Pro",
	"Samsung Galaxy A14",
	"Xiaomi Poco X5",
	"Xiaomi Redmi 10",
	"Xiaomi 12 Lite",
	"ZTE Blade A31",
	"ZTE Blade A31 Lite",
	"ZTE Blade V40 Vita",
	"ZTE Blade V40S",
	"ZTE Blade V40",
	"ZTE Blade A310",
	"ZTE",
}

func TestGalaxusClean(t *testing.T) {
	for i, name := range galaxusNames {
		if _name := shop.GalaxusCleanFn(name); _name != galaxusNamesExpected[i] {
			t.Errorf("given name \"%s\" not match expected name \"%s\"\n%s\n", _name, galaxusNamesExpected[i], name)
		}
	}
}
