package shop_test

import (
	shop "jsapi-scraper/shop"
	"testing"
)

var tuttiNames = []string{
	"****Galaxy Z Flip 3 5G****",
	"++ Realme GT Neo 3T Dragon Ball Z Edition Hammer Geil ++",
	"Iphone12 pro oro",
	"neuwertiges iPhone XS Max Rose 256GB",

	"2 Stuck  Iphone  7  128 GB",
	"Android Handy: INOI A63 (Neupreis 99CHF)",
	"Android Wiko Y80",
	"Apple iPhone SE | 32 GB | Space Gray | New Battery - Wie Neu",
	"Apple Iphone SE 4.7? 128 GB schwarz",
	"Apple iPhone X 65gb con vetro da sostituire",
	"Apple iPhone XS 64 Space Gray",
	"Apple iPhone Xs in exzellenten Zustand",
	"Apple I Phone 6 Plus Gold 16GB",
	"Apple I Phone 6S Space gray 32GB",
	"Apple I Phone X 64GB silber",
	"Blackwew A80 2GB RAM 16GB ROM",
	"Fairphone 1 2 Stück",
	"Fairphone 3 in guten Zustand zu verkaufen",
	"Für Einsteiger: iPhone SE 32Gb (1. Generation), Space Gray",
	"Galaxy A40 (Sehr guter Zustand",
	"gebrauchtes Xiaomi 9C",
	"Gebrauchtes Xiaomi Redmi 7A",
	"Google Pixel 2 5\" 64GB",
	"Google Pixel 3a mit 64 GB Speicher und Android 12",
	"Google Pixel 6 Pro Original OS, CalyxOS oder GrapheneOS",
	"Handy leicht gebraucht WIKO Y50",
	"Handy Redmi Note 10 Onyx Gray- Achtung! mit Glassbruch",
	"Handy - Oppo A53s electric black, 128 GB",
	"Handy / Smartphone Samsung Galaxy A3",
	"Handy / Smartphone: Samsung GT-E3210",
	"Handy/ Smartphone Xiaomi Redmi A1",
	"Handy/Natel Huawei P20",
	"Handy XIAOMI Redmi 9 - Dual-SIM 6.5 Zoll. 4GB RAM / 64GM,OVP",
	"Honor 10 / Dual-SIM / 64GB / LTE / USB-C / Earphone Jack",
	"Honor 7 PLK-L01 16GB",
	"Huawei Ascend Y 530 Black",
	"Huawei Mate 10 Pro BLA-L29 (EMUI 12)",
	"Huawei Nova 11i Starry Black Neuwertig mit Garantie",
	"Huawei P smart + zu verkaufen",
	"Huawei P10 lite DualSIM OVP",
	"Huawei P10 Plus VKY-L09",
	"HUAWEI P20 LITE HANDY/ GOOGLE FÄHIG",
	"Huawei P20 Lite 4 + 128GB Blu Dual SIM Smartphone",
	"Huawei P20 Perfetto Garanzia",
	"Huawei P30 lite New Version Black 6/256GB mit viel Zubehör",
	"Huawei P30 Pro New Edition 256GB",
	"HUAWEI P30 PRO GOOGLE SPERRE",
	"Huawei P30pro",
	"Huawei P30 lite NEW EDITION Breathing Crystal (Neuwertig)",
	"Huawei P-30 Lite 128 GB",
	"huawei P 30 lite",
	"HUAWEI P 40 LITE ,128 GB",
	"Huawei P40 lite Sakura Pink Neuwertig mit viel Zubehör!",
	"HUAWEI P9 FUNKTIONIERT EINWANDFREI.",
	"Huawei RIO-L01 GX8 Mystic 14 cm (5,5 Zoll) Smartphone (4G) silver",
	"Huawei y5, inkl. Original Ladegerät und Handbuch",
	"Huawei Y5p Smartphone NEU und OVP",
	"Huawei Y6 - 2018 - Dual (2) SIM 16GB ATU-L21,",
	"inoi A83 128+6GB",
	"I-Phone 5s + AirPods inkl. Zubehör",
	"I Phone 5 S",
	"I Phone 5 16G, Black",
	"I Phone 6 16 G Gold",
	"I Phone 8 64 G, silber",
	"i phone 10 xs",
	"I Phone SE 1. Generation 128 MB",
	"iPhone  6",
	"iPhone Apple 6S 32GB Gold - Guter Zustand",
	"iPhone X 256 weiss",
	"iPhone X con vetro da sostituire",
	"Iphone X funktionstüchtig / Jedoch mit Streifen",
	"Iphone X in einem sehr guten Zustand",
	"iPhone X. 256 GB",
	"iPhone XR10/white/ 64GB",
	"iPhone Xr; 256 GB; black; ohne SIM-Lock; tadelloser Zustand",
	"Iphone XR Ricondizionato Garanzia n.134",
	"IPHONE XR Yellow 128GB Garanzia n.172",
	"iPhone XR - neuwertiger Zustand",
	"Iphone XS (256 GB)",
	"IPhone XS in sehr gutem Zustand",
	"Iphone xs preis verhandelbar",
	"iPhone XS Max 512,",
	"iPhone SE2022 128 GB schwarz",
	"Iphone SE Gen 1 32GB in Schwarz",
	"iPhone SE 1 64GB",
	"iPhone SE 1 gen",
	"iPhone SE 1 Gen 64GB SpaceGray",
	"Iphone SE 1Gen  Rigenerato Garanzia",
	"Iphone SE 1st. Generation",
	"Iphone SE 1 Generation 32GB",
	"iPhone SE 1. GEN",
	"iPhone SE 1. gen 64gb",
	"iPhone SE 1. Generation 2016 16 GB",
	"Iphone SE 1. Generation gebraucht & gelöscht",
	"iPhone SE 2. Generation (2020) Rot",
	"Iphone SE 2. Gen (2022)",
	"IPhone SE 2",
	"Iphone SE 2016 (intakt, nur Touch Screen zersprungen)",
	"iPhone SE 2017 32GB",
	"Iphone SE 2020 Batteriekapazität 85%",
	"Iphone SE 2020 Red Edition Rot !! Gebraucht !!",
	"Iphone SE 2020/2022",
	"IPhone SE 54 GB gold",
	"IPhone SE 64GB Silber mit GARANTIE",
	"iPhone SE A1723 2016, Space Gray, 128GB",
	"iPhone SE and more",
	"Iphone SE année 2020 64Gb",
	"iPhone SE anno 2020",
	"iPhone SE in gutem Zustand",
	"iPhone SE im sehr guten Zustand mit Box",
	"iPhone SE Nero 128gb 128 gb 1 anno garanzia",
	"Iphone SE neu!!",
	"iPhone Se prima generazione",
	"iPhone SE primo modello",
	"Iphone SE RED",
	"iPhone SE Rosa 32GB",
	"iPhone SE rosagold",
	"Iphone SE Rosegold",
	"iPhone SE Roségold",
	"iphone se rose",
	"iPhone SE Rose Gold 64 GB 1. Generation",
	"Iphone SE Top Zustand RESERVIERT",
	"iphone se weiß",
	"iPhone SE mit Gebrauchsspuren",
	"iphone x 265 GB nur Verpackung",
	"iPhone XR 128",
	"Iphone XR 81% di batteria",
	"iPhone XR in rot 128 GB",
	"iphone XR mit OVP",
	"iphone xr red",
	"Iphone XR rot 64 GB",
	"IPHONE XS 64 BG",
	"iphone xs SIMLOCKED",
	"Iphone XSMax",
	"IPhone 10 64 GB",
	"iphone 11 bisschen kaputt aber geht noch gut",
	"iPhone 11 Pro 95% Batteriezustand",
	"iPhone 11 Pro Max 250 GB Midnight green",
	"Iphone 11 Red 64GB nur für 165.-",
	"Iphone 11 Red Product 64GB nur für 175.-",
	"iPhone 11 Speicher 64 GB",
	"Iphone 11 türkis - 64 GB",
	"iPhone 11 usato ma praticamente nuovo",
	"Iphone 11Pro 256GB Space Grey gebraucht",
	"iPhone 11pro Max in Gold, 64GB, gebraucht",
	"iPhone 12. 64 GB",
	"IPhone 12 64mg",
	"iPhone 12 blu 128 Gb",
	"iPhone 12 guter Zustand",
	"iPhone 12 Mini inklusive OVP",
	"iPhone 12 Pro in Pacific Blue",
	"iPhone 12 Pro Max Gehäuse Original",
	"iPhone 12 Pro Max Original Front Kamera Module",
	"iPhone 12 Pro Max Original Kamera Module",
	"iPhone 12 Pro Max Original Taptic Engine mit Lautsprecher",
	"iPhone 15 Pro Max ESR MagSafe, Armorite Glas, AirTag Loops",
	"ipohne 6 S, 64 GB",
	"Mi Xiaomi 10 Lite 5G",
	"Mobiltelefon Emporia 4G",
	"Moto G5G - wie neu, unbenutztes Zubehör",
	"Motorola e 20",
	"Motorola Edge 30 GRATIS VERSAND",
	"motorola edge 30 neo 24 Monate Garantie",
	"Motorola Moto G 6 mit Dual-SIM",
	"Motorolla V8 RAZR2 OVP",
	"Neues Galaxy a 13 Samsung GÜNSTIG",
	"Neues MOTOROLA Edge 20 Lite Smartphone (6.7 \", 128 GB",
	"Neuwertiges Handy Redmi 9a",
	"Nothing Phone (1), 8/256GB Schwarz, Garantie bis 13.2.25!",
	"NUOVO Iphone 12 mini bianco, 256gb",
	"One plus 8 pro 256GB 16GB",
	"Oppo A 1k",
	"Oppo A16 S in ottimo stato",
	"OPPO A54 Neu & ungeöffnet",
	"oppo a5 smartphone 6ram 128 rom",
	"OPPO A74-5G wie Neu",
	"Oppo A9 2020|4GB RAM|128 GB Speicher|Dual SIM",
	"Oppo find x 3 neo 12 G 256 ram pari al nuovo",
	"Oppo find x 3 neo 256GB",
	"Oppo Reno 6pro. 12GB/256GB",
	"Oppo Reno 8 8/256gb Schwarz neuwertig!",
	"Oppo reno 8 Lite Glasschaden",
	"ORIGINAL HUAWEI P40 MIT GOOGLE SERVICES",
	"Original SAMSUNG Galaxy NOTE 8 inkl. Stylus S PEN",
	"Pocophone F1 6GB/128GB 4G (mit neuer 4000mAh Batterie)",
	"POCOPHONE X3 NFC - Gebraucht, tadelloser Zustand",
	"Redmi 9C. 32 gb",
	"Redmi A2 di Xiaomi",
	"Redmi C9 128 GB",
	"Redmi Note 12 Pro (5G)",
	"Samsung A5-6",
	"samsung A 21 s",
	"Samsung A 51",
	"Samsung A13 garandieschein",
	"Samsung A2 Core Garanzia n.201",
	"Samsung A3,A5,A7,A8 Läuft Einwandfrei",
	"Samsung A50 in Weiss",
	"Samsung A52 s 5 G",
	"Samsung A7 (2018)",
	"Samsung galaxy a 20 e",
	"Samsung Galaxy A04 Copper Fabrikneu",
	"Samsung Galaxy A04e Hell Blau Fabrikneu",
	"Samsung Galaxy A13 Neuwertiger zustand (Preis auf Anfrage)",
	"Samsung Galaxy A14 praticamente nuovo",
	"Samsung Galaxy A3 in Lederetui mit Eingabestift",
	"Samsung Galaxy A3 2017 Occasion",
	"Sansung Galaxy A3 / 2017 goldig",
	"Samsung Galaxy A3/6 2016 schwarz",
	"Samsung Galaxy A32 5 G",
	"Samsung Galaxy A40 * black * 64GB * OVP",
	"Samsung Galaxy a40 Duos 64",
	"Samsung Galaxy A40 inkl. Ladegerät",
	"Samsung Galaxy A54 (5G, 256 GB)",
	"Samsung Galaxy a6 duas 32 GB",
	"Samsung Galaxy A7 Smartphone SM-A750FN/DS",
	"Samsung Galaxy A71 + accessori",
	"samsung Galaxy a8  Duos 32 GB mit Packung Ladekabel",
	"SAMSUNG Galaxy FE20 5G",
	"Samsung Galaxy J1 J100H White Android Smartphone",
	"Samsung Galaxy Note2 LTE GT-N7105 blau",
	"Samsung Galaxy Tablet A 6",
	"Samsung Galaxy Xcovet 5",
	"Samsung Galaxy ZFold3",
	"Samsung Galxy S3 mini 8GB",
	"Samsung GT-C3530 Chrome Silver - OVP - Ladegerät",
	"Samsung Mobile Phone - Galaxy J5 - Batteria rimovibile!!",
	"Samsung Note 9 512gb",
	"Samsung Note 10 Plus",
	"samsung s 10",
	"Samsung S 21 in Top Zustand ohne Kratzer",
	"Samsung Galaxy S Advance GT 19070",
	"Samsung S duos dual sim",
	"Samsung s10 - dual sim - 128 GB",
	"SAMSUNG S10 DUOS S10 NORMAL",
	"Samsung S10 und Huawei P8",
	"Samsung s21Ultra 5g",
	"Samsung s3 wie neu",
	"Samsung S6e Occassion Top Zustand",
	"Samsung S20 FE 5G",
	"Smartfon Huawei P8 lite 5 Zoll",
	"Smartphone - Honor 7X",
	"Smartphone Google Pixel - sehr guter Zustand",
	"Smartphone Huawei P9 EVA-L19",
	"Smartphone Inoi a 151",
	"Smartphone XIAOMI Redmi 9A ancora in Garanzia",
	"Sony Xperia 1 ll",
	"Sony Xperia 10iv",
	"Sony Xperia Handy einwandfrei",
	"Sony XPERIA Handy Telefon",
	"sony xperia modell f5321",
	"Sony Xperia xz F8331",
	"Sony XPERIA XZ2 4k kamera",
	"Sony Xperia Z3 Compact renoviert 4 Farben Gratisversand",
	"Sony Xperia Z5 Premium E6883",
	"Supper iPhone 11 Pro 256 GB Nachtgrün",
	"Telefon Xiomi Mi Note 10 Pro - 256GB",
	"Telefono per anziani Doro 7080",
	"Vendo iphone 11 rosso",
	"Vendo nuovo Redmi note 13 c 128gb",
	"VENDO SAMSUNG GALAXY NUOVO A14 4G, LUGANO",
	"Wiko Sunny 2 Dual SIM Neu nie benutzt",
	"Wiko Y60 Handy neuwertig",
	"Wiko Fever 4G (16Go/3Go) (neuf/neu)",
	"Wiko View3 , 64GB",
	"WIKO VIEW 4 LITE COMPLETO FUNZIONA BENISSIMO",
	"Xiaomi 11 T 128 GB in Cellular Blue",
	"Xiaomi Mi9",
	"Xiaomi MI9T 128GB, GB Ram, 48Mpx",
	"Xiaomi Mi 9 Litle",
	"xiaomi mi 9 Smartphone",
	"Xiaomi mobile redmi 10 blau chrome handy",
	"Xiaomi note 11 in usato",
	"Xiaomi Poco F4 256/8, Silber, 6.67",
	"Xiaomi POCO M5s [64GB / 4GB] Blau - NEU & OVP!",
	"Xiaomi Redmi 9 Note",
	"Xiaomi Redmi 9 a originalverpackt neu und OVP",
	"Xiaomi Redmi 9 a originalverpackt und OVP",
	"Xiaomi Redmi 9A 2GB 32 GB Grau 2 Jahre Garantie",
	"XIAOMI Redmi 9A HD+ Smartphone Android 32GB 13MP Nero",
	"Xiaomi Redmi 9a in OVP und noch verschweisst",
	"XIAOMI Redmi 9AT NUOVO!",
	"Xiaomi Redmi Note 8 Pro Pearl White",
	"Xiaomi Redmi Note 9 Pro Glacier White 128 GB",
	"Xiaomi Redmi Note 11 Graphite Gray 128GB 4GB RAM",
	"Xiaomi Redmi Note 11S 6/128",
	"Xiaomi Redmi Note 12 Glasschaden Funktioniert 100%",
	"Xiaomi Redmi Note5",
	"Zu verkaufen Honor 9Lite",
}

var tuttiNamesExpected = []string{
	"Samsung Galaxy Z Flip 3",
	"realme GT NEO 3T Dragon Ball Z Edition",
	"Apple iPhone 12 Pro",
	"Apple iPhone XS Max",

	"Apple iPhone 7",
	"Inoi A63",
	"Wiko Y80",
	"Apple iPhone SE",
	"Apple iPhone SE",
	"Apple iPhone X",
	"Apple iPhone XS",
	"Apple iPhone XS",
	"Apple iPhone 6 Plus",
	"Apple iPhone 6S",
	"Apple iPhone X",
	"Blackview A80",
	"Fairphone 1",
	"Fairphone 3",
	"Apple iPhone SE",
	"Samsung Galaxy A40",
	"Xiaomi Redmi 9C",
	"Xiaomi Redmi 7A",
	"Google Pixel 2",
	"Google Pixel 3a",
	"Google Pixel 6 Pro",
	"Wiko Y50",
	"Xiaomi Redmi Note 10",
	"OPPO A53s",
	"Samsung Galaxy A3",
	"Samsung GT-E3210",
	"Xiaomi Redmi A1",
	"HUAWEI P20",
	"Xiaomi Redmi 9",
	"HONOR 10",
	"HONOR 7",
	"HUAWEI Ascend Y530",
	"HUAWEI Mate 10 Pro",
	"HUAWEI nova 11i",
	"HUAWEI P smart+",
	"HUAWEI P10 lite",
	"HUAWEI P10 Plus",
	"HUAWEI P20 lite",
	"HUAWEI P20 lite",
	"HUAWEI P20",
	"HUAWEI P30 lite",
	"HUAWEI P30 Pro NE",
	"HUAWEI P30 Pro",
	"HUAWEI P30 Pro",
	"HUAWEI P30 lite NE",
	"HUAWEI P30 lite",
	"HUAWEI P30 lite",
	"HUAWEI P40 lite",
	"HUAWEI P40 lite",
	"HUAWEI P9",
	"HUAWEI GX8",
	"HUAWEI Y5",
	"HUAWEI Y5p",
	"HUAWEI Y6",
	"Inoi A83",
	"Apple iPhone 5S",
	"Apple iPhone 5S",
	"Apple iPhone 5",
	"Apple iPhone 6",
	"Apple iPhone 8",
	"Apple iPhone XS",
	"Apple iPhone SE (2016)",
	"Apple iPhone 6",
	"Apple iPhone 6S",
	"Apple iPhone X",
	"Apple iPhone X",
	"Apple iPhone X",
	"Apple iPhone X",
	"Apple iPhone X",
	"Apple iPhone XR",
	"Apple iPhone XR",
	"Apple iPhone XR",
	"Apple iPhone XR",
	"Apple iPhone XR",
	"Apple iPhone XS",
	"Apple iPhone XS",
	"Apple iPhone XS",
	"Apple iPhone XS Max",
	"Apple iPhone SE (2022)",
	"Apple iPhone SE (2016)",
	"Apple iPhone SE (2016)",
	"Apple iPhone SE (2016)",
	"Apple iPhone SE (2016)",
	"Apple iPhone SE (2016)",
	"Apple iPhone SE (2016)",
	"Apple iPhone SE (2016)",
	"Apple iPhone SE (2016)",
	"Apple iPhone SE (2016)",
	"Apple iPhone SE (2016)",
	"Apple iPhone SE (2016)",
	"Apple iPhone SE (2020)",
	"Apple iPhone SE (2020)",
	"Apple iPhone SE (2020)",
	"Apple iPhone SE (2016)",
	"Apple iPhone SE (2016)",
	"Apple iPhone SE (2020)",
	"Apple iPhone SE (2020)",
	"Apple iPhone SE (2020)",
	"Apple iPhone SE",
	"Apple iPhone SE",
	"Apple iPhone SE (2016)",
	"Apple iPhone SE",
	"Apple iPhone SE (2020)",
	"Apple iPhone SE (2020)",
	"Apple iPhone SE",
	"Apple iPhone SE",
	"Apple iPhone SE",
	"Apple iPhone SE",
	"Apple iPhone SE (2016)",
	"Apple iPhone SE (2016)",
	"Apple iPhone SE",
	"Apple iPhone SE",
	"Apple iPhone SE",
	"Apple iPhone SE",
	"Apple iPhone SE",
	"Apple iPhone SE",
	"Apple iPhone SE",
	"Apple iPhone SE",
	"Apple iPhone SE",
	"Apple iPhone SE",
	"Apple iPhone X",
	"Apple iPhone XR",
	"Apple iPhone XR",
	"Apple iPhone XR",
	"Apple iPhone XR",
	"Apple iPhone XR",
	"Apple iPhone XR",
	"Apple iPhone XS",
	"Apple iPhone XS",
	"Apple iPhone XS Max",
	"Apple iPhone X",
	"Apple iPhone 11",
	"Apple iPhone 11 Pro",
	"Apple iPhone 11 Pro Max",
	"Apple iPhone 11",
	"Apple iPhone 11",
	"Apple iPhone 11",
	"Apple iPhone 11",
	"Apple iPhone 11",
	"Apple iPhone 11 Pro",
	"Apple iPhone 11 Pro Max",
	"Apple iPhone 12",
	"Apple iPhone 12",
	"Apple iPhone 12",
	"Apple iPhone 12",
	"Apple iPhone 12 mini",
	"Apple iPhone 12 Pro",
	"Apple iPhone 12 Pro Max",
	"Apple iPhone 12 Pro Max",
	"Apple iPhone 12 Pro Max",
	"Apple iPhone 12 Pro Max",
	"Apple iPhone 15 Pro Max",
	"Apple iPhone 6S",
	"Xiaomi Mi 10 Lite",
	"emporia",
	"motorola moto g",
	"motorola moto e20",
	"motorola edge 30",
	"motorola edge 30 neo",
	"motorola moto g6",
	"motorola v8 razr2",
	"Samsung Galaxy A13",
	"motorola edge 20 lite",
	"Xiaomi Redmi 9A",
	"Nothing Phone (1)",
	"Apple iPhone 12 mini",
	"OnePlus 8 Pro",
	"OPPO A1k",
	"OPPO A16s",
	"OPPO A54",
	"OPPO A5",
	"OPPO A74",
	"OPPO A9 2020",
	"OPPO Find X3 Neo",
	"OPPO Find X3 Neo",
	"OPPO Reno6 Pro",
	"OPPO Reno8",
	"OPPO Reno8 Lite",
	"HUAWEI P40",
	"Samsung Galaxy Note8",
	"Xiaomi POCO F1",
	"Xiaomi POCO X3 NFC",
	"Xiaomi Redmi 9C",
	"Xiaomi Redmi A2",
	"Xiaomi Redmi 9C",
	"Xiaomi Redmi Note 12 Pro",
	"Samsung Galaxy A5",
	"Samsung Galaxy A21s",
	"Samsung Galaxy A51",
	"Samsung Galaxy A13",
	"Samsung Galaxy A2 Core",
	"Samsung Galaxy A3",
	"Samsung Galaxy A50",
	"Samsung Galaxy A52s",
	"Samsung Galaxy A7",
	"Samsung Galaxy A20e",
	"Samsung Galaxy A04",
	"Samsung Galaxy A04e",
	"Samsung Galaxy A13",
	"Samsung Galaxy A14",
	"Samsung Galaxy A3",
	"Samsung Galaxy A3",
	"Samsung Galaxy A3",
	"Samsung Galaxy A3",
	"Samsung Galaxy A32",
	"Samsung Galaxy A40",
	"Samsung Galaxy A40 Duos",
	"Samsung Galaxy A40",
	"Samsung Galaxy A54",
	"Samsung Galaxy A6 Duos",
	"Samsung Galaxy A7",
	"Samsung Galaxy A71",
	"Samsung Galaxy A8 Duos",
	"Samsung Galaxy S20 FE",
	"Samsung Galaxy J1",
	"Samsung Galaxy Note2",
	"Samsung Galaxy Tab A6",
	"Samsung Galaxy XCover 5",
	"Samsung Galaxy Z Fold 3",
	"Samsung Galaxy S3 mini",
	"Samsung GT-C3530",
	"Samsung Galaxy J5",
	"Samsung Galaxy Note9",
	"Samsung Galaxy Note10+",
	"Samsung Galaxy S10",
	"Samsung Galaxy S21",
	"Samsung Galaxy S Advance",
	"Samsung Galaxy S Duos",
	"Samsung Galaxy S10",
	"Samsung Galaxy S10 Duos",
	"Samsung Galaxy S10",
	"Samsung Galaxy S21 Ultra",
	"Samsung Galaxy S3",
	"Samsung Galaxy S6e",
	"Samsung Galaxy S20 FE",
	"HUAWEI P8 lite",
	"HONOR 7X",
	"Google Pixel",
	"HUAWEI P9",
	"Inoi A151",
	"Xiaomi Redmi 9A",
	"Sony Xperia 1 II",
	"Sony Xperia 10 IV",
	"Sony Xperia",
	"Sony Xperia",
	"Sony Xperia",
	"Sony Xperia XZ",
	"Sony Xperia XZ2",
	"Sony Xperia Z3 Compact",
	"Sony Xperia Z5 Premium",
	"Apple iPhone 11 Pro",
	"Xiaomi Mi Note 10 Pro",
	"Doro 7080",
	"Apple iPhone 11",
	"Xiaomi Redmi Note 13C",
	"Samsung Galaxy A14",
	"Wiko Sunny 2",
	"Wiko Y60",
	"Wiko Fever",
	"Wiko View 3",
	"Wiko View 4 Lite",
	"Xiaomi 11T",
	"Xiaomi Mi 9",
	"Xiaomi Mi 9T",
	"Xiaomi Mi 9 Lite",
	"Xiaomi Mi 9",
	"Xiaomi Redmi 10",
	"Xiaomi Redmi Note 11",
	"Xiaomi POCO F4",
	"Xiaomi POCO M5s",
	"Xiaomi Redmi Note 9",
	"Xiaomi Redmi 9A",
	"Xiaomi Redmi 9A",
	"Xiaomi Redmi 9A",
	"Xiaomi Redmi 9A",
	"Xiaomi Redmi 9A",
	"Xiaomi Redmi 9AT",
	"Xiaomi Redmi Note 8 Pro",
	"Xiaomi Redmi Note 9 Pro",
	"Xiaomi Redmi Note 11",
	"Xiaomi Redmi Note 11S",
	"Xiaomi Redmi Note 12",
	"Xiaomi Redmi Note 5",
	"HONOR 9 Lite",
}

func TestTuttiClean(t *testing.T) {
	for i, name := range tuttiNames {
		if _name := shop.TuttiCleanFn(name); _name != tuttiNamesExpected[i] {
			t.Errorf("given name \"%s\" not match expected name \"%s\"\n%s\n", _name, tuttiNamesExpected[i], name)
		}
	}
}
