package shop_test

import (
	shop "jsapi-scraper/shop"
	"testing"
)

var ultimusNames = []string{"Apple iPhone 11 Refurbished",
	"Apple iPhone 8 Plus Refurbished",
	"Apple iPhone 8 Refurbished",
	"Apple iPhone SE 2020 Refurbished",
	"Apple iPhone X Refurbished",
	"Blackview BV7200 Outdoor-Smartphone",
	"Blackview Oscal C80 Smartphone",
	"Fysic F15",
	"Fysic F25",
	"Gigaset GX4",
	"Honor Magic5 Lite",
	"Honor X7a",
	"Honor X8a",
	"HTC Desire 22 Pro",
	"Motorola Edge 20",
	"Motorola Edge 20 Lite 8GB",
	"Motorola Edge 30",
	"Motorola Edge 30 Neo",
	"Motorola Moto e13",
	"Motorola Moto e20",
	"Motorola Moto E22",
	"Motorola Moto E32s",
	"Motorola Moto e40",
	"Motorola Moto G13",
	"Motorola Moto G200 5G",
	"Motorola Moto G22",
	"Motorola Moto G23",
	"Motorola Moto G31",
	"Motorola Moto G32",
	"Motorola Moto G32 6GB",
	"Motorola Moto G41",
	"Motorola Moto G42",
	"Motorola Moto G51 5G",
	"Motorola Moto G52",
	"Motorola Moto G52 6GB",
	"Motorola Moto G53",
	"Motorola Moto G62",
	"Motorola Moto G72",
	"Motorola Moto G72 6GB",
	"Motorola Moto G73",
	"Motorola Moto G82 5G",
	"Nokia C2-2E",
	"Nokia G11",
	"Nokia G21",
	"Nokia G22",
	"Nokia G60 5G",
	"Nokia XR20",
	"Nothing Phone (1) 8GB",
	"OnePlus Nord 2T 8GB",
	"Oppo A16",
	"OPPO A57",
	"Oppo A74 5G",
	"Oppo A76",
	"Oppo A77",
	"Oppo A94",
	"Oppo A96 8GB",
	"Oppo Find X3 Lite",
	"Oppo Find X5 Lite",
	"Oppo Reno 7",
	"Oppo Reno 8 Lite",
	"Oppo Reno6 5G",
	"OPPO Reno8",
	"POCO C40 4GB Smartphone",
	"Poco M5",
	"Poco X5",
	"Poco X5 Pro",
	"Robustes Smartphone Blackview BV5200",
	"Samsung Galaxy A03s A037 3GB",
	"Samsung Galaxy A04s",
	"Samsung Galaxy A12 A127",
	"Samsung Galaxy A13",
	"Samsung Galaxy A13 A136 5G",
	"Samsung Galaxy A14",
	"Samsung Galaxy A14 5G",
	"Samsung Galaxy A22 5G",
	"Samsung Galaxy A23 A236",
	"Samsung Galaxy A32 4G A325",
	"Samsung Galaxy A32 5G A326",
	"Samsung Galaxy A33 5G A336",
	"Samsung Galaxy A34",
	"Samsung Galaxy A53 A536",
	"Samsung Galaxy M13",
	"Samsung Galaxy M23 5G M236",
	"Samsung Galaxy M33 M336",
	"Samsung Galaxy Xcover 5",
	"vivo V23",
	"Xiaomi 12 Lite 8GB",
	"Xiaomi Redmi 10",
	"Xiaomi Redmi 10 2022",
	"Xiaomi Redmi 10 5G",
	"Xiaomi Redmi 10C 3GB",
	"Xiaomi Redmi 12C 4GB",
	"Xiaomi Redmi 9C",
	"Xiaomi Redmi A1",
	"Xiaomi Redmi Note 11",
	"Xiaomi Redmi Note 11 Pro",
	"Xiaomi Redmi Note 11 Pro 5G",
	"Xiaomi Redmi Note 11S 6GB",
	"Xiaomi Redmi Note 12 Pro 6GB",
	"Xioami POCO M5s Smartphone",
}

var ultimusNamesExpected = []string{
	"Apple iPhone 11",
	"Apple iPhone 8 Plus",
	"Apple iPhone 8",
	"Apple iPhone SE (2020)",
	"Apple iPhone X",
	"Blackview BV7200",
	"Blackview Oscal C80",
	"Fysic F15",
	"Fysic F25",
	"Gigaset GX4",
	"HONOR Magic5 Lite",
	"HONOR X7a",
	"HONOR X8a",
	"HTC Desire 22 Pro",
	"motorola edge 20",
	"motorola edge 20 lite",
	"motorola edge 30",
	"motorola edge 30 neo",
	"motorola moto e13",
	"motorola moto e20",
	"motorola moto e22",
	"motorola moto e32s",
	"motorola moto e40",
	"motorola moto g13",
	"motorola moto g200",
	"motorola moto g22",
	"motorola moto g23",
	"motorola moto g31",
	"motorola moto g32",
	"motorola moto g32",
	"motorola moto g41",
	"motorola moto g42",
	"motorola moto g51",
	"motorola moto g52",
	"motorola moto g52",
	"motorola moto g53",
	"motorola moto g62",
	"motorola moto g72",
	"motorola moto g72",
	"motorola moto g73",
	"motorola moto g82",
	"Nokia C2-2E",
	"Nokia G11",
	"Nokia G21",
	"Nokia G22",
	"Nokia G60",
	"Nokia XR20",
	"Nothing Phone (1)",
	"OnePlus Nord 2T",
	"OPPO A16",
	"OPPO A57",
	"OPPO A74",
	"OPPO A76",
	"OPPO A77",
	"OPPO A94",
	"OPPO A96",
	"OPPO Find X3 Lite",
	"OPPO Find X5 Lite",
	"OPPO Reno7",
	"OPPO Reno8 Lite",
	"OPPO Reno6",
	"OPPO Reno8",
	"Xiaomi POCO C40",
	"Xiaomi POCO M5",
	"Xiaomi POCO X5",
	"Xiaomi POCO X5 Pro",
	"Blackview BV5200",
	"Samsung Galaxy A03s",
	"Samsung Galaxy A04s",
	"Samsung Galaxy A12",
	"Samsung Galaxy A13",
	"Samsung Galaxy A13",
	"Samsung Galaxy A14",
	"Samsung Galaxy A14",
	"Samsung Galaxy A22",
	"Samsung Galaxy A23",
	"Samsung Galaxy A32",
	"Samsung Galaxy A32",
	"Samsung Galaxy A33",
	"Samsung Galaxy A34",
	"Samsung Galaxy A53",
	"Samsung Galaxy M13",
	"Samsung Galaxy M23",
	"Samsung Galaxy M33",
	"Samsung Galaxy XCover 5",
	"vivo V23",
	"Xiaomi 12 Lite",
	"Xiaomi Redmi 10",
	"Xiaomi Redmi 10 2022",
	"Xiaomi Redmi 10",
	"Xiaomi Redmi 10C",
	"Xiaomi Redmi 12C",
	"Xiaomi Redmi 9C",
	"Xiaomi Redmi A1",
	"Xiaomi Redmi Note 11",
	"Xiaomi Redmi Note 11 Pro",
	"Xiaomi Redmi Note 11 Pro",
	"Xiaomi Redmi Note 11S",
	"Xiaomi Redmi Note 12 Pro",
	"Xiaomi POCO M5s",
}

func TestUltimusClean(t *testing.T) {
	for i, name := range ultimusNames {
		if _name := shop.UltimusCleanFn(name); _name != ultimusNamesExpected[i] {
			t.Errorf("given name \"%s\" not match expected name \"%s\"\n%s\n", _name, ultimusNamesExpected[i], name)
		}
	}
}
